version: "3.9"
services:
  db:
    container_name: riderize_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    user: root
