name: Continuous Integration

on: [push]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm install
      - run: npm run test
      - run: npm run build
